### ISSUE TITLE
Unable to use Test Link XML-RPC API due to 404 Not Found - https://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php

### ISSUE THREAD

**Issue by cmatthey** [bitnami/bitnami-docker-testlink#90]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

I am not able to use Test Link XML-RPC API with a Python client due to 404 Not Found of the link https://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php when I tested this TestLink bitnami docker on my local laptop. I am going to describe two ways to reproduce it. One if the origin problem that with a python client.

**Steps to reproduce the issue:**

1. [Enable API in the config]
Edit /opt/bitnami/testlink/config.ini.php file so it has the following config
$tlCfg->api->enabled = TRUE;
$tlCfg->exec_cfg->enabled_test_automation = ENABLED;
2. [Enable API in the test project]
Generate API Key in Test Project Management
3. [Generate a user api token]
Copy the token from Personal API access key in the My Settings
3. [Connect to TestLink API via Python client]
pip3 install Python client from here https://pypi.org/project/TestLink-API-Python-client/
Follow the steps in the instruction of the above Python client
set TESTLINK_API_PYTHON_SERVER_URL=http://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php
set TESTLINK_API_PYTHON_DEVKEY=xxx
python
>>> import testlink
>>> tls = testlink.TestLinkHelper().connect(testlink.TestlinkAPIClient)
>>> tls.countProjects()

problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php

**Describe the results you received:**

I am receiving a 404 Not Found. Here is the trace.

Traceback (most recent call last):
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkapigeneric.py", line 2057, in _callServer
    response = getattr(self.server.tl, methodNameAPI)(argsAPI)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkapi.py", line 392, in countProjects
    projects=self.getProjects()
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkdecorators.py", line 140, in wrapperReplaceTLResponseError
    response = methodAPI(self, *argsPositional, **argsOptional)
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkdecorators.py", line 112, in wrapperAddDevKey
    return methodAPI(self, *argsPositional, **argsOptional)
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkdecorators.py", line 100, in wrapperWithArgs
    *argsPositional, **argsOptional)
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkapigeneric.py", line 1582, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "/home/coco/.virtualenvs/jira/lib/python3.6/site-packages/testlink/testlinkapigeneric.py", line 2061, in _callServer
    raise testlinkerrors.TLConnectionError(new_msg)
testlink.testlinkerrors.TLConnectionError: problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>

**Describe the results you expected:**

A number indicating connection success and return back the number of projects. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
docker version 
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-65-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.49GiB
Name: thinkpad
ID: HBZY:4J4B:WAL7:NU5L:T47F:2YFD:OZJY:EJU5:RAAG:HI5H:AYEB:FNMO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support


```

- Output of `docker-compose version` (if applicable):

```
 docker-compose version
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
 docker image inspect bitnami/testlink:1
[
    {
        "Id": "sha256:80800fda5d3dfe8bd08bf29c6d2aa8fca14650c2099bca1719e5031247993274",
        "RepoTags": [
            "bitnami/testlink:1"
        ],
        "RepoDigests": [
            "bitnami/testlink@sha256:e648c731ebb8657803e4dab369f04ed7060d275b8f4ac4d0a3999c489b8d148f"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-10-29T16:03:31.608250528Z",
        "Container": "3d44aabd9a87a6f5ce700b6818e3d317e644d485e7c78c045bc0d4c488617a49",
        "ContainerConfig": {
            "Hostname": "3d44aabd9a87",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/bitnami/apache/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/mysql/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "IMAGE_OS=debian-9",
                "NAMI_VERSION=1.0.0-1",
                "GPG_KEY_SERVERS_LIST=ha.pool.sks-keyservers.net                          hkp://p80.pool.sks-keyservers.net:80                          keyserver.ubuntu.com                          hkp://keyserver.ubuntu.com:80                          pgp.mit.edu",
                "TINI_VERSION=v0.13.2",
                "TINI_GPG_KEY=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7",
                "GOSU_VERSION=1.10",
                "GOSU_GPG_KEY=B42F6819007F00F88E364FD4036A9C25BF357DD4",
                "BITNAMI_IMAGE_VERSION=1.9.19-debian-9-r245",
                "ALLOW_EMPTY_PASSWORD=no",
                "BITNAMI_APP_NAME=testlink",
                "MARIADB_HOST=mariadb",
                "MARIADB_PORT_NUMBER=3306",
                "MARIADB_ROOT_PASSWORD=",
                "MARIADB_ROOT_USER=root",
                "MYSQL_CLIENT_CREATE_DATABASE_NAME=",
                "MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=",
                "MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL",
                "MYSQL_CLIENT_CREATE_DATABASE_USER=",
                "SMTP_CONNECTION_MODE=",
                "SMTP_ENABLE=false",
                "SMTP_HOST=",
                "SMTP_PASSWORD=",
                "SMTP_PORT=",
                "SMTP_USER=",
                "TESTLINK_DATABASE_NAME=bitnami_testlink",
                "TESTLINK_DATABASE_PASSWORD=",
                "TESTLINK_DATABASE_USER=bn_testlink",
                "TESTLINK_EMAIL=user@example.com",
                "TESTLINK_LANGUAGE=en_US",
                "TESTLINK_PASSWORD=bitnami",
                "TESTLINK_USERNAME=user"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"nami\" \"start\" \"--foreground\" \"apache\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:5c395f249352832a6c1cb0a435a2a7a6acfc07430e72c3119a402175e9eda71a",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/app-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {
                "maintainer": "Bitnami <containers@bitnami.com>"
            }
        },
        "DockerVersion": "18.09.3",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/bitnami/apache/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/mysql/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "IMAGE_OS=debian-9",
                "NAMI_VERSION=1.0.0-1",
                "GPG_KEY_SERVERS_LIST=ha.pool.sks-keyservers.net                          hkp://p80.pool.sks-keyservers.net:80                          keyserver.ubuntu.com                          hkp://keyserver.ubuntu.com:80                          pgp.mit.edu",
                "TINI_VERSION=v0.13.2",
                "TINI_GPG_KEY=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7",
                "GOSU_VERSION=1.10",
                "GOSU_GPG_KEY=B42F6819007F00F88E364FD4036A9C25BF357DD4",
                "BITNAMI_IMAGE_VERSION=1.9.19-debian-9-r245",
                "ALLOW_EMPTY_PASSWORD=no",
                "BITNAMI_APP_NAME=testlink",
                "MARIADB_HOST=mariadb",
                "MARIADB_PORT_NUMBER=3306",
                "MARIADB_ROOT_PASSWORD=",
                "MARIADB_ROOT_USER=root",
                "MYSQL_CLIENT_CREATE_DATABASE_NAME=",
                "MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=",
                "MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL",
                "MYSQL_CLIENT_CREATE_DATABASE_USER=",
                "SMTP_CONNECTION_MODE=",
                "SMTP_ENABLE=false",
                "SMTP_HOST=",
                "SMTP_PASSWORD=",
                "SMTP_PORT=",
                "SMTP_USER=",
                "TESTLINK_DATABASE_NAME=bitnami_testlink",
                "TESTLINK_DATABASE_PASSWORD=",
                "TESTLINK_DATABASE_USER=bn_testlink",
                "TESTLINK_EMAIL=user@example.com",
                "TESTLINK_LANGUAGE=en_US",
                "TESTLINK_PASSWORD=bitnami",
                "TESTLINK_USERNAME=user"
            ],
            "Cmd": [
                "nami",
                "start",
                "--foreground",
                "apache"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:5c395f249352832a6c1cb0a435a2a7a6acfc07430e72c3119a402175e9eda71a",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/app-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {
                "maintainer": "Bitnami <containers@bitnami.com>"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 391994755,
        "VirtualSize": 391994755,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/4df4a794d8d08bee6a5cced038e202519d52c77e5d0f8a14662d3c57ecfa8842/diff:/var/lib/docker/overlay2/a61a538f41900e223a2d55702432a57b54ce5b24d070a73c2b70f1d776685387/diff:/var/lib/docker/overlay2/42d2088717c7483a3f618cb7a5cdd02f4035a4db1a5448168048fa959aa9b0e2/diff:/var/lib/docker/overlay2/72ee05ca66b2887ae917122132579a1decb1bef6d04bb00839f124237fceb8e0/diff:/var/lib/docker/overlay2/e1b40fbef3e8ee2a1dd7b1eb9bdc1c2bcee9d67ba7e730f4ba1fc5a5aa0b4ced/diff:/var/lib/docker/overlay2/f54825c9623041f91288542c4cd9c9b89b20f7db7c33ff719479d79e2acf50d4/diff:/var/lib/docker/overlay2/cc820f734082b2195e2a39c5adbc5295c44efe039e9b70991a7b2367fd6b77e4/diff:/var/lib/docker/overlay2/a4b403234412ffb2a09a77c01a70f8720a02478a6edd73166a7f2b184e4ad3fd/diff:/var/lib/docker/overlay2/18c3ff4b53537027e080b6fc848d0257fdb23167990eac84194729483269b9c7/diff:/var/lib/docker/overlay2/8c24cadd28d18574062415394874975e9f26a5001b29c1be1eeb92e3c7e86cf2/diff:/var/lib/docker/overlay2/0cbd747be287260d2fe1a76c27d5bc91cccfc450a29c889eccf0a6b381834c1f/diff:/var/lib/docker/overlay2/aff4e07b5b8de13b28972d7a3b32cdb1c797075e84561e4137891d81c07d7ae7/diff:/var/lib/docker/overlay2/bff59ddc25020affb425ab3178451c6d2e54852787125e9f44e0814b300d8a01/diff",
                "MergedDir": "/var/lib/docker/overlay2/fbf85be24c4c5a07b1739b1d973afdee22c64a09db4f6039e5f7ae9f6358eec7/merged",
                "UpperDir": "/var/lib/docker/overlay2/fbf85be24c4c5a07b1739b1d973afdee22c64a09db4f6039e5f7ae9f6358eec7/diff",
                "WorkDir": "/var/lib/docker/overlay2/fbf85be24c4c5a07b1739b1d973afdee22c64a09db4f6039e5f7ae9f6358eec7/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:3005072043ee8393cb92946b772ff71d3e714545aeca4d233e1d328b7af88806",
                "sha256:4e8b3d98fb6ada1fb0b15ef3559bcd7069dd6036a999ef6648e46eb7f966fa56",
                "sha256:de1cf6c4aeddbdb8b7fd6aa58c4782cad86822c040ad94ac70b3b70703478778",
                "sha256:0541934ddbecc3e7eaeda3df4b2cd9507f2a7b2b54589af2a720668908b97c0c",
                "sha256:d24f2a16996a8591b6df8de86b99e6616cebf6d3476fb6c0b50a75ba5e877910",
                "sha256:d56c5bf833fc821fd0efe7a0fa5b83b9b9e0ba6ac48c39e999ec9f1671d2458f",
                "sha256:d8d5e57e0cbbbda24e621880b708effb0c7a26c086d5d511cdc23be92fee0981",
                "sha256:d69d50cb43d481ff71c804cb483021ae2acb660210b30409aa781e22e32c94cf",
                "sha256:dcd1fc8f863b0bed2cb028c5dbaa1eb64ae1046a18ca2f4fa9bb7473cbc8b559",
                "sha256:7b1f8de855d5c6bf52da30557e308f8ec269ac6a6722bb4fae286f729daec386",
                "sha256:5bbe45a77d935fb76a108c213a168f148b87a125fd25f2344e2e311418d13e5f",
                "sha256:ae72f63564d0969f096f6962675aba14dd7b4f9db3703b41198fa6ac71e1b69e",
                "sha256:cc3e2ac6b54f376000b833c18c2452c6bc914b9ec56d66d83bd4cb3419b114e4",
                "sha256:3c21d115574e1502d9e5373dd44290a80a835e12a2a35facc3fc247d28ce94ef"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by cmatthey** [comment]
This can be closed. It turned out to be a 3rd party documentation error. It should be https://localhost/lib/api/xmlrpc/v1/xmlrpc.php not https://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php.
